### ISSUE TITLE
event-stream korkattu, kannattanee päivittää dependencyt..

### ISSUE THREAD

**Issue by pakastin** [koodiklinikka/koodiklinikka.fi#37]
https://github.com/koodiklinikka/koodiklinikka.fi/blob/028724def44b75d4d3f939623e52e5fa87a69e1a/package.json#L48

https://github.com/dominictarr/event-stream/issues/116

**Comment by pakastin** [comment]
https://twitter.com/npm_support/status/1067139332178407424

**Comment by rikukissa** [comment]
thaanks, will do
