### ISSUE TITLE
Clearer error message when user already exists with an email

### ISSUE THREAD

**Issue by rikukissa** [koodiklinikka/koodiklinikka.fi#38]
![image](https://user-images.githubusercontent.com/1206987/53789962-69590d00-3f2e-11e9-9249-dd80db4fbe84.png)

Backend should return a better error code and a message that could be identified in the frontend as a "duplicate user" error. From there we could then show a different error message to the user

**Comment by peritpatrio** [comment]
Do we want to leak whether a user with an email address X has already joined or not?
