### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by n1koo** [koodiklinikka/koodiklinikka.fi#5]
In the spirit of HTTP/2 and HTTPS everywhere lets get SSL going.

Options on implementing this:

- Buy a cert ( ~20/year )
- Get free one from https://www.startssl.com/
 - Have to manually renewed every year
- Put koodiklinikka.fi behind a service that offers SAN's. Like cloudflare

**Comment by japsu** [comment]
Let's do this right the first time and make the site an example of good SSL practices for the members:

* SHA-256 hash in the certificate
* Strong SSL settings in nginx (PFS, secured against downgrade attacks, AES-GCM, ECDHE)
* HTTP Strict Transport Security headers
* screw the old browsers ;) ;)
* etc.

[Mozilla recommended TLS settings](https://wiki.mozilla.org/Security/Server_Side_TLS#Nginx) are a good place to start. Should get A+ from [SSL Labs' test](https://www.ssllabs.com/ssltest).

**Comment by n1koo** [comment]
:+1: @japsu 

I can handle that on the weekend probably. I can also grab a free cert from Startssl since if we want to it really secure we can't really rely on service like cloudflare which also have think about compatiblity.

**Comment by japsu** [comment]
:+1:

**Comment by n1koo** [comment]
A+ from  [SSL Labs' test](https://www.ssllabs.com/ssltest)

Free cert (1year) from startssl installed.

For config: https://github.com/koodiklinikka/playbooks/blob/master/files/nginx/ssl_profile.conf

**Comment by japsu** [comment]
:+1:
